---
# install (package)
- include: "setup-{{ansible_os_family|lower}}.yml"

# add configs
- name: template exabgp.env
  template:
    src: exabgp.env.j2
    dest: /etc/exabgp/exabgp.env
  notify: restart exabgp

- name: template exabgp.conf
  template:
    src: exabgp.conf.j2
    dest: /etc/exabgp/exabgp.conf
  notify: reload exabgp

# and go, go, go
- name: enable and start exabgp
  service:
    name: exabgp
    enabled: yes
  when: exabgp_start|default(true)
