---
- name: copy over the packages
  copy: src=exabgp-rpms dest=/var/tmp

- name: install the packages (locally)
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - /var/tmp/exabgp-rpms/python-exabgp-3.4.20-2.el7.centos.noarch.rpm
    - /var/tmp/exabgp-rpms/exabgp-3.4.20-2.el7.centos.noarch.rpm
    - python-setuptools
    - python-ipaddr
    - bind-utils

- name: create path for pid file
  file:
    path: "{{ exabgp_pid_file |dirname }}"
    state: directory
    owner: "{{ exabgp_user }}"
    group: "{{ exabgp_group }}"
    mode: 0755

- name: fix permissions on etc directory
  file:
    path: /etc/exabgp
    state: directory
    owner: "root"
    group: "{{ exabgp_group }}"
    mode: 0754
