---
- name: copy over the packages
  copy: src=exabgp-rpms dest=/var/tmp

- name: install the packages (locally)
  yum:
    name: "{{item}}"
    state: installed
  with_items:
    - /var/tmp/exabgp-rpms/python-exabgp-3.4.20-1.el7.centos.noarch.rpm
    - /var/tmp/exabgp-rpms/exabgp-3.4.20-1.el7.centos.noarch.rpm

- name: create path for pid file
  file:
    path: /var/run/exabgp
    state: directory
    owner: "{{ exabgp_user }}"
    group: "{{ exabgp_group }}"
    mode: 0755
