---
- name: restart exabgp
  service: 
    name: exabgp
    state: restarted
  when: "{{ exabgp_start|default(True) }}"

- name: reload exabgp
  service: 
    name: exabgp
    state: reloaded
  when: "{{ exabgp_start|default(True) }}"

